# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
